/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorArchivos;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author NANCY
 */
public class VentanaIngresarTexto extends javax.swing.JInternalFrame {

    private ControladorArchivos controladorArchivos;
    /**
     * Creates new form VentanaIngresarTexto
     */
    public VentanaIngresarTexto(ControladorArchivos controladorArchivos) {
        initComponents();
        
        this.controladorArchivos= controladorArchivos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRuta = new javax.swing.JTextField();
        btnJFileChooser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDeTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreArchivo = new javax.swing.JTextField();
        btnGuardarArchivo = new javax.swing.JButton();

        txtRuta.setEditable(false);
        txtRuta.setBackground(new java.awt.Color(255, 255, 204));

        btnJFileChooser.setText("...");
        btnJFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJFileChooserActionPerformed(evt);
            }
        });

        txtAreaDeTexto.setColumns(20);
        txtAreaDeTexto.setRows(5);
        jScrollPane1.setViewportView(txtAreaDeTexto);

        jLabel1.setText("Ruta:");

        jLabel2.setText("Nombre del archivo:");

        btnGuardarArchivo.setText("Guardar Archivo ");
        btnGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarArchivo)
                            .addComponent(btnJFileChooser))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJFileChooser)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJFileChooserActionPerformed
        JFileChooser fc= new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion= fc.showOpenDialog(this);
        
        if(seleccion==JFileChooser.APPROVE_OPTION ){
            File archivo= fc.getSelectedFile();
            txtRuta.setText(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_btnJFileChooserActionPerformed

    private void btnGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArchivoActionPerformed
        String ruta=txtRuta.getText();
        String nombre= txtNombreArchivo.getText();
        if(!ruta.isEmpty() && !nombre.isEmpty()){
            String nombreEncriptado = controladorArchivos.encriptarNombreArchivo(nombre);
            System.out.println(ruta);
            String texto=txtAreaDeTexto.getText();
            System.out.println(texto);
            controladorArchivos.crearArchivoDeTexto(ruta,nombreEncriptado,texto);
            JOptionPane.showMessageDialog(this, "Texto guardado exitosamente");
            limpiar();
        }else{
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        }
    }//GEN-LAST:event_btnGuardarArchivoActionPerformed

    public void limpiar(){
        txtAreaDeTexto.setText("");
        txtNombreArchivo.setText("");
        txtRuta.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarArchivo;
    private javax.swing.JButton btnJFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaDeTexto;
    private javax.swing.JTextField txtNombreArchivo;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables
}
